import type { AIRegulationFramework, SecurityRequirement } from './types'

export const REGULATION_LABELS: Record<AIRegulationFramework, string> = {
  'oecd-ai-principles': 'OECD AI Principles',
  'unesco-ai-ethics': 'UNESCO AI Ethics',
  'iso-42001': 'ISO 42001',
  'eu-ai-act': 'EU AI Act',
  gdpr: 'GDPR',
  'nist-ai-rmf': 'NIST AI RMF',
  'white-house-eo': 'US AI Executive Order',
  ccpa: 'CCPA',
  hipaa: 'HIPAA',
  sox: 'SOX',
  ferpa: 'FERPA',
  glba: 'GLBA',
  'au-ai-strategy': 'AU AI Continental Strategy',
  'au-data-policy': 'AU Data Policy Framework',
  'smart-africa': 'Smart Africa AI Blueprint',
  'sa-ai-policy-draft': 'SA AI Policy (Draft)',
  popia: 'POPIA',
  ecta: 'ECTA',
  dmre: 'DMRE (SA Mining)',
  sahpra: 'SAHPRA',
  dora: 'DORA',
  nis2: 'NIS2 Directive',
  fedramp: 'FedRAMP',
  finra: 'FINRA',
  cpra: 'CPRA',
  'fda-samd': 'FDA SaMD',
  soc2: 'SOC 2',
  'iso-27001': 'ISO 27001',
  msha: 'MSHA',
  epa: 'EPA',
  osha: 'OSHA',
  'nerc-cip': 'NERC CIP',
  'pci-dss': 'PCI DSS',
  'au-ai-ethics-framework': 'AU AI Ethics Framework',
  'brazil-lgpd': 'Brazil LGPD',
  'brazil-ai-bill': 'Brazil AI Bill',
  'singapore-ai-governance': 'Singapore AI Governance',
  'uk-ai-regulation': 'UK AI Regulation',
  'canada-aida': 'Canada AIDA',
  'japan-ai-strategy': 'Japan AI Strategy',
  'india-dpdp': 'India DPDP Act',
  'uae-ai-strategy': 'UAE AI Strategy',
  'kenya-dpa': 'Kenya DPA',
  'nigeria-ndpr': 'Nigeria NDPR',
  'china-ai-regulations': 'China AI Regulations',
  'ms-responsible-ai': 'MS Responsible AI',
  'ms-ai-principles': 'MS AI Principles',
  'ms-copilot-governance': 'MS Copilot Governance',
  other: 'Other',
}

export const RISK_LEVEL_LABELS: Record<string, string> = {
  unacceptable: 'Unacceptable Risk',
  high: 'High Risk',
  limited: 'Limited Risk',
  minimal: 'Minimal Risk',
}

export const SECURITY_REQUIREMENT_LABELS: Record<SecurityRequirement, string> = {
  'encryption-at-rest': 'Encryption at Rest',
  'encryption-in-transit': 'Encryption in Transit',
  'access-control': 'Access Control',
  'audit-logging': 'Audit Logging',
  'penetration-testing': 'Penetration Testing',
  'vulnerability-scanning': 'Vulnerability Scanning',
  'data-masking': 'Data Masking',
  'mfa-required': 'MFA Required',
  'soc2-compliance': 'SOC 2 Compliance',
  iso27001: 'ISO 27001',
  'zero-trust': 'Zero Trust',
  'air-gapped': 'Air-Gapped',
  'on-premises-only': 'On-Premises Only',
  'scada-protection': 'SCADA/ICS Protection',
}

export const DATA_CLASSIFICATION_LABELS: Record<string, string> = {
  public: 'Public',
  internal: 'Internal',
  confidential: 'Confidential',
  'highly-confidential': 'Highly Confidential',
  pii: 'PII (Personal Data)',
  phi: 'PHI (Health Data)',
  financial: 'Financial',
  operational: 'Operational/Industrial',
}
