/**
 * MCEM pipeline domain model.
 *
 * This is the spine of the distilled app. It models the journey the subsidiary
 * actually cares about:
 *
 *   generate a PIPELINE of candidate use cases
 *     -> account teams (ATU) VALIDATE them with the customer
 *       -> SURVIVING use cases become OPPORTUNITIES that get worked on
 *         -> opportunities progress through MCEM Stage 1 -> 4
 *           -> Stage 4 is the HANDSHAKE to CSU (not CSU delivery work)
 *
 * Stages covered: 1 (ATU) -> 4 (handshake to CSU). The Customer Success work
 * that happens AFTER the handshake is intentionally out of scope.
 *
 * Types + constant metadata live here. Behaviour (gates, transitions,
 * promotion, status derivation) lives in `mcem-engine.ts`.
 */

import type { UseCase } from './types'

// ============================================================================
// SALES ROLES — ATU -> STU -> CSU
// ============================================================================

/** Microsoft field sales role units that own work across the MCEM stages. */
export type SalesRole = 'ATU' | 'STU' | 'CSU'

export interface SalesRoleMeta {
  role: SalesRole
  /** Full name, e.g. "Account Team Unit". */
  name: string
  /** Personas that sit in this unit. */
  personas: string[]
  /** One-line description of what the unit owns in this tool. */
  description: string
}

export const SALES_ROLES: Record<SalesRole, SalesRoleMeta> = {
  ATU: {
    role: 'ATU',
    name: 'Account Team Unit',
    personas: ['Account Executive', 'Account Technology Strategist (ATS)'],
    description:
      'Owns the customer relationship. Generates and validates the use-case pipeline with the customer.',
  },
  STU: {
    role: 'STU',
    name: 'Solution / Specialist Team Unit',
    personas: ['Specialist', 'Solution Engineer', 'Technical Specialist'],
    description:
      'Scopes surviving use cases into solutions and builds the business case for commitment.',
  },
  CSU: {
    role: 'CSU',
    name: 'Customer Success Unit',
    personas: ['Cloud Solution Architect (CSA)'],
    description:
      'Receives the committed opportunity at the Stage 4 handshake and owns delivery (out of scope here).',
  },
}

// ============================================================================
// MCEM STAGES — 1 -> 4
// ============================================================================

/** The MCEM stages this tool covers: 1 (Listen & Consult) -> 4 (Handshake). */
export type McemStage = 1 | 2 | 3 | 4

export type McemStageKey =
  | 'listen-consult'
  | 'inspire-design'
  | 'empower-achieve'
  | 'handshake'

export interface McemStageMeta {
  stage: McemStage
  key: McemStageKey
  /** Official-ish MCEM name, e.g. "Listen & Consult". */
  name: string
  /** Short verb label used on the pipeline board, e.g. "Discover". */
  shortName: string
  /** The role primarily accountable for moving work through this stage. */
  owningRole: SalesRole
  /** Plain-language goal for this stage. */
  goal: string
}

export const MCEM_STAGE_ORDER: McemStage[] = [1, 2, 3, 4]

export const MCEM_STAGES: Record<McemStage, McemStageMeta> = {
  1: {
    stage: 1,
    key: 'listen-consult',
    name: 'Listen & Consult',
    shortName: 'Discover',
    owningRole: 'ATU',
    goal: 'Generate and validate a pipeline of use cases with the customer.',
  },
  2: {
    stage: 2,
    key: 'inspire-design',
    name: 'Inspire & Design',
    shortName: 'Design',
    owningRole: 'STU',
    goal: 'Scope surviving use cases into a solution the customer is excited by.',
  },
  3: {
    stage: 3,
    key: 'empower-achieve',
    name: 'Empower & Achieve',
    shortName: 'Prove',
    owningRole: 'STU',
    goal: 'Build the business case and secure customer commitment.',
  },
  4: {
    stage: 4,
    key: 'handshake',
    name: 'Realize Value — Handshake',
    shortName: 'Handshake',
    owningRole: 'CSU',
    goal: 'Hand the committed opportunity to the CSU (CSA). Delivery itself is out of scope.',
  },
}

// ============================================================================
// USE-CASE PIPELINE FUNNEL
// ============================================================================

/**
 * Where a use case sits in the funnel. Derived (not stored) from the use
 * case's `disposition` / `problemConfirmed` and whether it has been promoted
 * into an Opportunity — see `getUseCasePipelineStatus` in `mcem-engine.ts`.
 */
export type UseCasePipelineStatus =
  /** Generated by discovery, not yet validated with the customer. */
  | 'candidate'
  /** Customer confirmed the problem and it survives (disposition = pursue). */
  | 'validated'
  /** Promoted into an Opportunity that is being worked. */
  | 'promoted'
  /** Deferred or no-go'd — retained for the audit trail, out of the pipeline. */
  | 'parked'

export const USE_CASE_PIPELINE_STATUS_LABELS: Record<UseCasePipelineStatus, string> = {
  candidate: 'Candidate',
  validated: 'Validated',
  promoted: 'Opportunity',
  parked: 'Parked',
}

// ============================================================================
// OPPORTUNITY — a surviving use case (or bundle) being worked through MCEM
// ============================================================================

/** Status of an Opportunity as it moves through the MCEM stages. */
export type OpportunityStatus =
  /** Stage 1 — qualifying the validated use case(s). */
  | 'qualifying'
  /** Stage 2 — designing / scoping the solution. */
  | 'designing'
  /** Stage 3 — proving value & securing commitment. */
  | 'proving'
  /** Stage 4 — gate met, handshake prepared, awaiting CSU acceptance. */
  | 'handoff-ready'
  /** Stage 4 — CSU (CSA) has accepted the handshake. */
  | 'handed-off'
  /** Dropped at any stage. */
  | 'closed-lost'

export const OPPORTUNITY_STATUS_LABELS: Record<OpportunityStatus, string> = {
  qualifying: 'Qualifying',
  designing: 'Designing',
  proving: 'Proving',
  'handoff-ready': 'Handoff ready',
  'handed-off': 'Handed off',
  'closed-lost': 'Closed (lost)',
}

/** A single recorded stage transition, for the opportunity audit trail. */
export interface StageTransition {
  id: string
  /** Stage moved from (null for the initial promotion into Stage 1). */
  from: McemStage | null
  to: McemStage
  at: number
  /** Role that performed the transition. */
  byRole: SalesRole
  /** Optional person name. */
  by?: string
  note?: string
}

/** One item on the Stage 4 handshake checklist. */
export interface HandoffChecklistItem {
  id: string
  label: string
  done: boolean
}

/**
 * Stage 4 handshake package handed to the CSU (CSA). This captures the
 * handshake itself — not the delivery work the CSA does afterwards.
 */
export interface HandoffPackage {
  preparedAt: number
  preparedBy?: string
  summary?: string
  checklist: HandoffChecklistItem[]
  /** CSA who accepts the handshake. */
  csaName?: string
  acceptedAt?: number
  acceptedBy?: string
}

/**
 * An Opportunity is one or more *validated* use cases being progressed
 * through MCEM. Default is 1 use case : 1 opportunity, but several related
 * use cases can be bundled into a single opportunity.
 */
export interface Opportunity {
  id: string
  customerId: string
  /** Discovery session the surviving use case(s) came from. */
  discoverySessionId?: string
  name: string
  /** The validated use case(s) this opportunity is built from (1..N). */
  useCaseIds: string[]
  stage: McemStage
  status: OpportunityStatus
  /** Role currently accountable (derived from stage at creation, can be overridden). */
  owningRole: SalesRole
  /** Current owner's name. */
  owner?: string
  /** Stage 4 handshake package (present once prepared). */
  handoff?: HandoffPackage
  /** Append-only audit trail of stage transitions. */
  history: StageTransition[]
  createdAt: number
  updatedAt: number
}

// ============================================================================
// STAGE GATES
// ============================================================================

/** A single requirement that must be met to clear a stage gate. */
export interface GateRequirement {
  id: string
  label: string
  met: boolean
  /** Short hint on how to satisfy this requirement. */
  hint?: string
}

/** Result of evaluating the gate for an opportunity's current stage. */
export interface StageGateResult {
  stage: McemStage
  requirements: GateRequirement[]
  /** True when every requirement is met (the opportunity can advance). */
  ready: boolean
  /** 0..1 completion ratio, for progress UI. */
  completion: number
}

/**
 * A use case "survives" customer validation when it has not been deferred or
 * ruled out. `disposition` is undefined by default, which we treat as still
 * pursuable.
 */
export function isUseCaseSurviving(uc: Pick<UseCase, 'disposition'>): boolean {
  return uc.disposition !== 'defer' && uc.disposition !== 'no-go'
}
