import type { ArchitectureDiagramSpecV1 } from '@/lib/architecture-diagrams'

function escapeMermaidLabel(label: string): string {
  return label
    .replace(/\r?\n/g, ' ')
    .replace(/"/g, "'")
    .trim()
}

export function diagramSpecToMermaidFlowchart(spec: ArchitectureDiagramSpecV1): string {
  // Guardrails: only allow our supported version
  if (spec.version !== 1) {
    throw new Error(`Unsupported diagram spec version: ${spec.version}`)
  }

  const direction = spec.direction
  const lines: string[] = []

  lines.push(`flowchart ${direction}`)
  lines.push('%% Generated by KARABO (JSON → Mermaid)')
  if (spec.title) {
    lines.push(`%% ${escapeMermaidLabel(spec.title)}`)
  }

  // Build lookups
  const nodesByGroup = new Map<string, Array<{ id: string; label: string; kind?: string }>>()
  for (const group of spec.groups) {
    nodesByGroup.set(group.id, [])
  }
  for (const node of spec.nodes) {
    if (!node.groupId) continue
    const arr = nodesByGroup.get(node.groupId)
    if (arr) arr.push({ id: node.id, label: node.label, kind: node.kind })
  }

  // Groups/subgraphs
  for (const group of [...spec.groups].sort((a, b) => a.order - b.order)) {
    const groupNodes = nodesByGroup.get(group.id) ?? []
    const title = escapeMermaidLabel(group.label)
    lines.push(`subgraph ${group.id}["${title}"]`)
    lines.push('direction TB')

    // Render anchor as a circle, services as boxes
    for (const node of groupNodes) {
      if (node.kind === 'anchor') {
        lines.push(`${node.id}(("${escapeMermaidLabel(node.label)}"))`)
      }
    }

    for (const node of groupNodes) {
      if (node.kind === 'service') {
        lines.push(`${node.id}["${escapeMermaidLabel(node.label)}"]`)
      }
    }

    lines.push('end')
  }

  // Edges
  for (const edge of spec.edges) {
    const arrow = edge.kind === 'dashed' ? '-.->' : '-->'
    const label = edge.label ? `|"${escapeMermaidLabel(edge.label)}"|` : ''
    lines.push(`${edge.from} ${arrow}${label} ${edge.to}`)
  }

  // Light styling
  lines.push('classDef tierAnchor fill:#111827,color:#fff,stroke:#111827,stroke-width:1px;')
  lines.push('classDef serviceNode fill:#ffffff,color:#111827,stroke:#94a3b8,stroke-width:1px;')

  for (const node of spec.nodes) {
    if (node.kind === 'anchor') lines.push(`class ${node.id} tierAnchor`)
    if (node.kind === 'service') lines.push(`class ${node.id} serviceNode`)
  }

  return lines.join('\n')
}

let mermaidInitPromise: Promise<void> | null = null

async function ensureMermaidInitialized(theme: 'default' | 'dark' = 'default'): Promise<any> {
  const mermaid = (await import('mermaid')).default

  if (!mermaidInitPromise) {
    mermaidInitPromise = (async () => {
      mermaid.initialize({
        startOnLoad: false,
        securityLevel: 'strict',
        theme,
        flowchart: {
          htmlLabels: false,
          useMaxWidth: true,
        },
      })
    })()
  }

  // Mermaid theme is set at init time; if theme changes, re-init.
  // Keep it simple: reinitialize when theme differs.
  if ((mermaid as any).__karaboTheme !== theme) {
    mermaid.initialize({
      startOnLoad: false,
      securityLevel: 'strict',
      theme,
      flowchart: {
        htmlLabels: false,
        useMaxWidth: true,
      },
    })
    ;(mermaid as any).__karaboTheme = theme
  }

  await mermaidInitPromise
  return mermaid
}

export async function renderMermaidToSvg(mermaidText: string, theme: 'default' | 'dark' = 'default'): Promise<string> {
  const mermaid = await ensureMermaidInitialized(theme)
  const id = `m_${Math.random().toString(36).slice(2)}`

  const res = await mermaid.render(id, mermaidText)
  return typeof res === 'string' ? res : res.svg
}

export async function renderMermaidToPngDataUrl(mermaidText: string, opts?: {
  width?: number
  height?: number
  theme?: 'default' | 'dark'
  background?: string
}): Promise<{ dataUrl: string; width: number; height: number }> {
  const width = opts?.width ?? 1200
  const height = opts?.height ?? 700
  const theme = opts?.theme ?? 'default'
  const background = opts?.background ?? '#ffffff'

  const svg = await renderMermaidToSvg(mermaidText, theme)
  const { Canvg } = await import('canvg')

  const canvas = document.createElement('canvas')
  canvas.width = width
  canvas.height = height

  const ctx = canvas.getContext('2d')
  if (!ctx) throw new Error('Canvas 2D context not available')

  // Fill background for PDF compatibility
  ctx.fillStyle = background
  ctx.fillRect(0, 0, width, height)

  const v = await Canvg.fromString(ctx, svg)
  await v.render()

  return {
    dataUrl: canvas.toDataURL('image/png'),
    width,
    height,
  }
}
