/**
 * Four sample CSAM scenarios (Section 13). These power demo mode and let every
 * cockpit page render with realistic, non-customer data.
 *
 *  A. Microsoft 365 Copilot licences purchased but low active usage
 *  B. Azure migration completed but cost optimisation poor
 *  C. Fabric capacity purchased but no production data products
 *  D. Security workloads deployed but incidents remain high
 */
import type { CsamCustomerProfile } from './types'

const now = Date.now()
const months = (n: number) => now - n * 30 * 24 * 60 * 60 * 1000

// ============================================================================
// A. M365 Copilot — licences purchased, low active usage
// ============================================================================

const copilot: CsamCustomerProfile = {
  customerId: 'demo-copilot',
  name: 'Northwind Traders',
  industry: 'Retail',
  segment: 'enterprise',
  region: 'EU',
  executivePriorities: ['Lift frontline productivity', 'Reduce cost-to-serve', 'Protect margin'],
  team: { csam: 'A. Mokoena', ae: 'J. Pereira', specialist: 'R. Singh' },
  renewalSignal: 'amber',
  source: 'demo',
  lastUpdated: now,
  investments: [
    {
      id: 'inv-cop-1',
      customerId: 'demo-copilot',
      solutionArea: 'm365-copilot',
      product: 'Microsoft 365 Copilot',
      purchaseType: 'license',
      purchasePeriodStart: months(7),
      committedValueUSD: 1_200_000,
      intendedOutcome: 'Save 3-5 hours/week per knowledge worker; lift sales and service productivity.',
      sponsor: 'COO',
      businessOwner: 'VP Sales Ops',
      technicalOwner: 'M365 Admin Lead',
      financeOwner: 'FP&A Director',
      relatedSuccessPlan: 'FY26 Productivity Plan',
      relatedCsdrTopic: 'M365 Copilot adoption heatmap',
      risks: ['Low active usage vs. licences assigned'],
      classification: 'internal',
    },
  ],
  usageSignals: [
    {
      id: 'use-cop-1',
      investmentId: 'inv-cop-1',
      licensesPurchased: 4000,
      licensesAssigned: 3200,
      activeUsers: 900,
      usageTrend: 'flat',
      intensityScore: 28,
      adoptionGapPct: 72,
      telemetrySource: 'M365 admin usage reports',
      classification: 'internal',
      confidence: 'medium',
      asOf: months(1),
    },
  ],
  useCases: [
    {
      id: 'uc-cop-1',
      customerId: 'demo-copilot',
      name: 'Copilot for sales & service teams',
      businessProblem: 'Reps spend hours on email, summaries and CRM updates instead of selling.',
      persona: 'Sales & service reps',
      process: 'Account follow-up and CRM hygiene',
      expectedOutcome: '3-5 hours/week returned to selling',
      solutionArea: 'm365-copilot',
      technology: 'Microsoft 365 Copilot',
      adoptionStage: 'assigned',
      linkedInvestmentId: 'inv-cop-1',
      behaviouralBarriers: ['tool-not-embedded', 'weak-manager-reinforcement', 'unclear-wiifm'],
      healthDependencies: ['telemetry-completeness'],
    },
  ],
  financialImpacts: [
    {
      id: 'fin-cop-1',
      useCaseId: 'uc-cop-1',
      statementType: 'income',
      lineItem: 'G&A expense (productivity)',
      expectedDirection: 'decrease',
      mechanism: 'Hours returned to revenue-generating work reduce cost-to-serve per account.',
      metric: 'Hours saved/week per active user; revenue per employee',
      confidence: 'low',
      validationStatus: 'hypothesis',
      evidenceAvailable: 'Vendor usage telemetry',
      evidenceMissing: 'Customer time-use baseline and finance validation',
      dataOwner: 'FP&A Director',
      validationQuestion: 'Can we baseline hours spent on follow-up before vs. after for a pilot team?',
    },
  ],
  healthSignals: [
    {
      id: 'hl-cop-1',
      customerId: 'demo-copilot',
      dimension: 'telemetry-completeness',
      status: 'amber',
      riskLevel: 'medium',
      businessImpact: 'Partial usage visibility limits value proof.',
      recommendation: 'Enable full M365 usage analytics and a Copilot dashboard.',
      microsoftOwner: 'CSAM',
      reviewCadence: 'Monthly',
      includeInCsdr: true,
    },
  ],
  adoption: [
    {
      id: 'ad-cop-1',
      customerId: 'demo-copilot',
      useCaseId: 'uc-cop-1',
      scores: { awareness: 55, desire: 45, knowledge: 40, ability: 35, reinforcement: 25, 'workflow-integration': 30, 'executive-modelling': 35 },
      blockers: ['tool-not-embedded', 'weak-manager-reinforcement', 'unclear-wiifm'],
      notes: 'High licence assignment, low embedding in the selling workflow.',
    },
  ],
  actions: [],
}

// ============================================================================
// B. Azure migration completed, cost optimisation poor
// ============================================================================

const azure: CsamCustomerProfile = {
  customerId: 'demo-azure',
  name: 'Tailspin Aerospace',
  industry: 'Manufacturing',
  segment: 'enterprise',
  region: 'US',
  executivePriorities: ['Improve free cash flow', 'Cloud cost discipline', 'Scale reliably'],
  team: { csam: 'L. van Wyk', ats: 'D. Okafor', csa: 'P. Andersson' },
  renewalSignal: 'green',
  source: 'demo',
  lastUpdated: now,
  investments: [
    {
      id: 'inv-az-1',
      customerId: 'demo-azure',
      solutionArea: 'azure-compute',
      product: 'Azure IaaS/PaaS (post-migration)',
      purchaseType: 'cloud-consumption',
      purchasePeriodStart: months(14),
      committedValueUSD: 6_000_000,
      intendedOutcome: 'Exit data centres; pay-as-you-go elasticity and lower TCO.',
      sponsor: 'CIO',
      businessOwner: 'Head of Infrastructure',
      technicalOwner: 'Cloud Platform Lead',
      financeOwner: 'VP Finance',
      relatedCsdrTopic: 'Consumption reporting & FinOps',
      risks: ['Idle/oversized resources inflating OPEX'],
      classification: 'internal',
    },
  ],
  usageSignals: [
    {
      id: 'use-az-1',
      investmentId: 'inv-az-1',
      workloadConsumptionUSD: 420_000,
      usageTrend: 'rising',
      intensityScore: 70,
      adoptionGapPct: 20,
      telemetrySource: 'Azure Cost Management',
      confidence: 'high',
      asOf: months(1),
    },
  ],
  useCases: [
    {
      id: 'uc-az-1',
      customerId: 'demo-azure',
      name: 'FinOps & cost optimisation',
      businessProblem: 'Migrated workloads are oversized and under-governed; spend is climbing.',
      persona: 'Platform & FinOps team',
      process: 'Cloud cost governance',
      expectedOutcome: '15-25% run-rate reduction without performance loss',
      solutionArea: 'azure-compute',
      technology: 'Azure Cost Management, Advisor, reservations',
      adoptionStage: 'activated',
      linkedInvestmentId: 'inv-az-1',
      behaviouralBarriers: ['no-workflow-redesign', 'incentives-reward-old'],
      healthDependencies: ['cost-optimisation', 'governance-readiness'],
    },
  ],
  financialImpacts: [
    {
      id: 'fin-az-1',
      useCaseId: 'uc-az-1',
      statementType: 'income',
      lineItem: 'IT operating expense',
      expectedDirection: 'decrease',
      mechanism: 'Rightsizing, reservations and autoscale reduce monthly run-rate.',
      metric: 'Azure run-rate ($/month); cost per workload',
      baseline: 420_000,
      target: 320_000,
      confidence: 'medium',
      validationStatus: 'in-validation',
      evidenceAvailable: 'Azure Cost Management baseline',
      evidenceMissing: 'Agreed savings target signed off by finance',
      dataOwner: 'VP Finance',
      validationQuestion: 'Can we agree a rightsizing target and track it monthly?',
    },
    {
      id: 'fin-az-2',
      useCaseId: 'uc-az-1',
      statementType: 'cash-flow',
      lineItem: 'Free cash flow',
      expectedDirection: 'increase',
      mechanism: 'Lower run-rate and reservation timing improve operating cash flow.',
      metric: 'Operating cash flow; avoided capex',
      confidence: 'low',
      validationStatus: 'hypothesis',
      evidenceMissing: 'Finance confirmation of cash impact',
      dataOwner: 'Treasury',
      validationQuestion: 'Does shifting capex to consumption help your working-capital cycle?',
    },
  ],
  healthSignals: [
    {
      id: 'hl-az-1',
      customerId: 'demo-azure',
      dimension: 'cost-optimisation',
      status: 'red',
      riskLevel: 'high',
      businessImpact: 'Idle and oversized resources inflate OPEX ~20-30%.',
      financialExposure: 'IT operating expense',
      recommendation: 'Run a FinOps optimisation review (rightsizing + reservations).',
      customerOwner: 'Cloud Platform Lead',
      microsoftOwner: 'CSA',
      reviewCadence: 'Monthly',
      includeInCsdr: true,
    },
    {
      id: 'hl-az-2',
      customerId: 'demo-azure',
      dimension: 'governance-readiness',
      status: 'amber',
      riskLevel: 'medium',
      businessImpact: 'No tagging/budget policy; cost accountability is unclear.',
      recommendation: 'Introduce tagging, budgets and a cost-owner model.',
      microsoftOwner: 'CSA',
      reviewCadence: 'Quarterly',
      includeInCsdr: true,
    },
  ],
  adoption: [
    {
      id: 'ad-az-1',
      customerId: 'demo-azure',
      useCaseId: 'uc-az-1',
      scores: { awareness: 70, desire: 60, knowledge: 55, ability: 50, reinforcement: 40, incentives: 30, 'workflow-integration': 45 },
      blockers: ['no-workflow-redesign', 'incentives-reward-old'],
    },
  ],
  actions: [],
}

// ============================================================================
// C. Fabric capacity purchased, no production data products
// ============================================================================

const fabric: CsamCustomerProfile = {
  customerId: 'demo-fabric',
  name: 'Contoso Health',
  industry: 'Healthcare',
  segment: 'majors-growth',
  region: 'ZA',
  executivePriorities: ['Faster time-to-insight', 'Lower reporting cost', 'Data-driven care'],
  team: { csam: 'T. Nkosi', ae: 'S. Petrov' },
  renewalSignal: 'amber',
  source: 'demo',
  lastUpdated: now,
  investments: [
    {
      id: 'inv-fab-1',
      customerId: 'demo-fabric',
      solutionArea: 'fabric',
      product: 'Microsoft Fabric capacity (F64)',
      purchaseType: 'subscription',
      purchasePeriodStart: months(5),
      committedValueUSD: 540_000,
      intendedOutcome: 'Consolidate analytics; ship production data products and self-serve BI.',
      sponsor: 'Chief Data Officer',
      businessOwner: 'Head of Analytics',
      technicalOwner: 'Data Platform Lead',
      financeOwner: 'Finance Business Partner',
      relatedCsdrTopic: 'Realised value & data product backlog',
      risks: ['Capacity paid for but idle; no production data products yet'],
      classification: 'internal',
    },
  ],
  usageSignals: [
    {
      id: 'use-fab-1',
      investmentId: 'inv-fab-1',
      workloadConsumptionUSD: 12_000,
      usageTrend: 'flat',
      intensityScore: 18,
      adoptionGapPct: 80,
      telemetrySource: 'Fabric capacity metrics',
      confidence: 'medium',
      asOf: months(1),
    },
  ],
  useCases: [
    {
      id: 'uc-fab-1',
      customerId: 'demo-fabric',
      name: 'Production data products on Fabric',
      businessProblem: 'Reporting is slow and manual; analysts wait days for data.',
      persona: 'Analysts & clinical ops',
      process: 'Reporting and decision support',
      expectedOutcome: 'Self-serve data products; hours-not-days time-to-insight',
      solutionArea: 'fabric',
      technology: 'Microsoft Fabric (Lakehouse, Power BI)',
      adoptionStage: 'purchased',
      linkedInvestmentId: 'inv-fab-1',
      behaviouralBarriers: ['no-workflow-redesign', 'lack-exec-sponsorship', 'low-awareness'],
      healthDependencies: ['telemetry-completeness'],
    },
  ],
  financialImpacts: [
    {
      id: 'fin-fab-1',
      useCaseId: 'uc-fab-1',
      statementType: 'income',
      lineItem: 'Cost of service (reporting effort)',
      expectedDirection: 'decrease',
      mechanism: 'Self-serve data products cut manual report-building effort.',
      metric: 'Analyst hours/report; time-to-insight',
      confidence: 'low',
      validationStatus: 'hypothesis',
      evidenceMissing: 'Baseline of current reporting effort & cost',
      dataOwner: 'Head of Analytics',
      validationQuestion: 'How many analyst hours go into recurring reports today?',
    },
  ],
  healthSignals: [
    {
      id: 'hl-fab-1',
      customerId: 'demo-fabric',
      dimension: 'operational-maturity',
      status: 'red',
      riskLevel: 'high',
      businessImpact: 'Capacity is idle; no production data products shipped.',
      financialExposure: 'Cost of service',
      recommendation: 'Prioritise a Fabric data-product backlog and ship 1-2 to production.',
      customerOwner: 'Data Platform Lead',
      microsoftOwner: 'CSA',
      reviewCadence: 'Bi-weekly',
      includeInCsdr: true,
    },
  ],
  adoption: [
    {
      id: 'ad-fab-1',
      customerId: 'demo-fabric',
      useCaseId: 'uc-fab-1',
      scores: { awareness: 35, desire: 50, knowledge: 30, ability: 25, reinforcement: 20, 'executive-modelling': 30 },
      blockers: ['no-workflow-redesign', 'lack-exec-sponsorship', 'low-awareness'],
    },
  ],
  actions: [],
}

// ============================================================================
// D. Security workloads deployed, incidents remain high
// ============================================================================

const security: CsamCustomerProfile = {
  customerId: 'demo-security',
  name: 'Fabrikam Financial',
  industry: 'Financial Services',
  segment: 'enterprise',
  region: 'EU',
  executivePriorities: ['Reduce risk exposure', 'Regulatory resilience', 'Protect brand'],
  team: { csam: 'G. Botha', ats: 'M. Haddad', csa: 'N. Dlamini' },
  renewalSignal: 'red',
  source: 'demo',
  lastUpdated: now,
  investments: [
    {
      id: 'inv-sec-1',
      customerId: 'demo-security',
      solutionArea: 'sentinel',
      product: 'Microsoft Sentinel + Defender XDR',
      purchaseType: 'cloud-consumption',
      purchasePeriodStart: months(9),
      committedValueUSD: 2_400_000,
      intendedOutcome: 'Faster detection & response; reduce incident frequency and dwell time.',
      sponsor: 'CISO',
      businessOwner: 'SOC Manager',
      technicalOwner: 'Security Engineering Lead',
      financeOwner: 'Risk & Finance',
      relatedCsdrTopic: 'Security posture & resiliency',
      risks: ['Incident volume still high; tuning incomplete'],
      classification: 'confidential',
    },
  ],
  usageSignals: [
    {
      id: 'use-sec-1',
      investmentId: 'inv-sec-1',
      workloadConsumptionUSD: 95_000,
      usageTrend: 'rising',
      intensityScore: 55,
      adoptionGapPct: 45,
      telemetrySource: 'Sentinel / Defender telemetry',
      classification: 'confidential',
      confidence: 'medium',
      asOf: months(1),
    },
  ],
  useCases: [
    {
      id: 'uc-sec-1',
      customerId: 'demo-security',
      name: 'Detection & response maturity',
      businessProblem: 'High incident volume and slow response despite tooling deployed.',
      persona: 'SOC analysts',
      process: 'Threat detection & incident response',
      expectedOutcome: 'Lower incident frequency and mean-time-to-respond',
      solutionArea: 'sentinel',
      technology: 'Sentinel, Defender XDR, automation playbooks',
      adoptionStage: 'activated',
      linkedInvestmentId: 'inv-sec-1',
      behaviouralBarriers: ['no-workflow-redesign', 'poor-training-relevance'],
      healthDependencies: ['security-posture', 'incident-readiness', 'major-incident-readiness'],
    },
  ],
  financialImpacts: [
    {
      id: 'fin-sec-1',
      useCaseId: 'uc-sec-1',
      statementType: 'income',
      lineItem: 'Security / compliance / risk cost',
      expectedDirection: 'avoid',
      mechanism: 'Faster detection lowers breach probability and incident handling cost.',
      metric: 'Incidents/month; mean-time-to-respond; value-at-risk',
      confidence: 'medium',
      validationStatus: 'in-validation',
      evidenceAvailable: 'Incident telemetry trend',
      evidenceMissing: 'Agreed risk-cost model with Risk & Finance',
      dataOwner: 'Risk & Finance',
      validationQuestion: 'What is your modelled cost per incident / value-at-risk?',
    },
    {
      id: 'fin-sec-2',
      useCaseId: 'uc-sec-1',
      statementType: 'balance-sheet',
      lineItem: 'Provisions / contingent liabilities',
      expectedDirection: 'protect',
      mechanism: 'Stronger posture reduces expected regulatory/contingent exposure.',
      metric: 'Open high-severity findings; audit status',
      confidence: 'low',
      validationStatus: 'hypothesis',
      evidenceMissing: 'Risk function validation',
      dataOwner: 'Chief Risk Officer',
      validationQuestion: 'How do you provision for cyber/regulatory risk today?',
    },
  ],
  healthSignals: [
    {
      id: 'hl-sec-1',
      customerId: 'demo-security',
      dimension: 'security-posture',
      status: 'red',
      riskLevel: 'critical',
      businessImpact: 'High-severity findings remain open; exposure elevated.',
      financialExposure: 'Security / compliance / risk cost',
      recommendation: 'Initiate a security posture review and tune detections.',
      customerOwner: 'Security Engineering Lead',
      microsoftOwner: 'CSA',
      reviewCadence: 'Weekly',
      includeInCsdr: true,
    },
    {
      id: 'hl-sec-2',
      customerId: 'demo-security',
      dimension: 'incident-readiness',
      status: 'amber',
      riskLevel: 'high',
      businessImpact: 'Response runbooks/playbooks incomplete; MTTR above target.',
      recommendation: 'Complete automation playbooks and run an incident exercise.',
      microsoftOwner: 'CSA',
      reviewCadence: 'Monthly',
      includeInCsdr: true,
    },
    {
      id: 'hl-sec-3',
      customerId: 'demo-security',
      dimension: 'reactive-support',
      status: 'amber',
      riskLevel: 'medium',
      businessImpact: 'Repeated support cases on the same detection gaps.',
      recommendation: 'Root-cause the repeated cases via a proactive review.',
      microsoftOwner: 'Support',
      reviewCadence: 'Monthly',
      includeInCsdr: false,
    },
  ],
  adoption: [
    {
      id: 'ad-sec-1',
      customerId: 'demo-security',
      useCaseId: 'uc-sec-1',
      scores: { awareness: 65, desire: 70, knowledge: 50, ability: 45, reinforcement: 40, 'workflow-integration': 40 },
      blockers: ['no-workflow-redesign', 'poor-training-relevance'],
    },
  ],
  actions: [],
}

export const DEMO_CSAM_PROFILES: CsamCustomerProfile[] = [copilot, azure, fabric, security]
