import { useState } from 'react'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group'
import { Separator } from '@/components/ui/separator'
import { FilePdf, Envelope, Printer, CheckCircle, MicrosoftPowerpointLogo, MicrosoftTeamsLogo, MicrosoftOutlookLogo } from '@phosphor-icons/react'
import { toast } from 'sonner'
import { exportSessionToPptx } from '@/lib/pptx-export'
import { openTeamsShare, openOutlookCompose, buildTeamsSummary } from '@/lib/share-helpers'

export interface ExportDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onExportPDF: (effortUnit: 'person-weeks' | 'fte' | 'man-hours') => void
  // Optional session data for email export
  sessionData?: {
    customerName: string
    industry?: string
    summary?: string
    useCases?: Array<{
      title: string
      description: string
      priority?: number
      rice?: { score?: number }
      coiEstimate?: { totalAnnualCOI?: number }
      effortPersonWeeks?: number
    }>
    nextSteps?: string[]
    microsoftSolutions?: string[]
    businessCase?: {
      investmentUSD?: number
      threeYearBenefitUSD?: number
      paybackMonths?: number
      npvUSD?: number
    }
  }
}

export function ExportDialog({ open, onOpenChange, onExportPDF, sessionData }: ExportDialogProps) {
  const [effortUnit, setEffortUnit] = useState<'person-weeks' | 'fte' | 'man-hours'>('person-weeks')
  const [emailCopied, setEmailCopied] = useState(false)

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value)
  }

  const handleCopyEmailHTML = async () => {
    if (!sessionData) {
      toast.error('No session data available for email export')
      return
    }

    const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    h2 { color: #1a1a2e; border-bottom: 2px solid #0066cc; padding-bottom: 8px; }
    h3 { color: #0066cc; margin-top: 24px; }
    table { border-collapse: collapse; width: 100%; margin: 16px 0; }
    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
    th { background-color: #f5f5f5; font-weight: 600; }
    tr:nth-child(even) { background-color: #fafafa; }
    .priority-high { color: #059669; font-weight: 600; }
    .coi { color: #dc2626; }
    .summary { background-color: #f0f9ff; padding: 16px; border-radius: 8px; margin: 16px 0; }
  </style>
</head>
<body>
  <h2>Discovery Summary: ${sessionData.customerName}</h2>
  
  ${sessionData.summary ? `
  <div class="summary">
    <h3>Executive Summary</h3>
    <p>${sessionData.summary.replace(/\n/g, '<br>')}</p>
  </div>
  ` : ''}
  
  ${sessionData.useCases && sessionData.useCases.length > 0 ? `
  <h3>Prioritized Use Cases</h3>
  <table>
    <tr>
      <th>#</th>
      <th>Use Case</th>
      <th>Description</th>
      <th>RICE Score</th>
      <th>Annual COI</th>
    </tr>
    ${sessionData.useCases.slice(0, 10).map((uc, i) => `
    <tr>
      <td class="priority-high">${i + 1}</td>
      <td><strong>${uc.title}</strong></td>
      <td>${uc.description}</td>
      <td>${uc.rice?.score?.toFixed(1) || 'N/A'}</td>
      <td class="coi">${uc.coiEstimate?.totalAnnualCOI ? formatCurrency(uc.coiEstimate.totalAnnualCOI) : 'N/A'}</td>
    </tr>
    `).join('')}
  </table>
  ` : ''}
  
  ${sessionData.nextSteps && sessionData.nextSteps.length > 0 ? `
  <h3>Recommended Next Steps</h3>
  <ol>
    ${sessionData.nextSteps.map(step => `<li>${step}</li>`).join('')}
  </ol>
  ` : ''}
  
  <p style="color: #666; font-size: 12px; margin-top: 32px; border-top: 1px solid #ddd; padding-top: 16px;">
    Generated by ID-8 Discovery Tool | ${new Date().toLocaleDateString()}
  </p>
</body>
</html>
    `.trim()

    try {
      await navigator.clipboard.writeText(html)
      setEmailCopied(true)
      toast.success('Email HTML copied to clipboard!')
      setTimeout(() => setEmailCopied(false), 3000)
    } catch (error) {
      toast.error('Failed to copy to clipboard')
    }
  }

  const handlePrintPDF = () => {
    window.print()
    toast.info('Print dialog opened - select "Save as PDF" to save')
  }

  const handleExportPPTX = async () => {
    if (!sessionData) { toast.error('No session data available'); return }
    try {
      await exportSessionToPptx({
        customerName: sessionData.customerName,
        industry: sessionData.industry,
        executiveSummary: sessionData.summary,
        useCases: (sessionData.useCases || []).map((u) => ({
          title: u.title,
          description: u.description,
          riceScore: u.rice?.score,
          annualCoiUSD: u.coiEstimate?.totalAnnualCOI,
          effortPersonWeeks: u.effortPersonWeeks,
        })),
        businessCase: sessionData.businessCase,
        nextSteps: sessionData.nextSteps,
        microsoftSolutions: sessionData.microsoftSolutions,
      })
      toast.success('PowerPoint deck downloaded')
    } catch (err: any) {
      toast.error(`PPTX export failed: ${err?.message || String(err)}`)
    }
  }

  const handleShareTeams = () => {
    if (!sessionData) { toast.error('No session data available'); return }
    openTeamsShare({
      message: buildTeamsSummary({
        customerName: sessionData.customerName,
        topUseCases: (sessionData.useCases || []).slice(0, 5).map((u) => ({
          title: u.title, annualCoiUSD: u.coiEstimate?.totalAnnualCOI,
        })),
        threeYearBenefitUSD: sessionData.businessCase?.threeYearBenefitUSD,
        paybackMonths: sessionData.businessCase?.paybackMonths,
      }),
      topic: `Karabo Discovery — ${sessionData.customerName}`,
    })
    toast.success('Opening Teams…')
  }

  const handleShareOutlook = () => {
    if (!sessionData) { toast.error('No session data available'); return }
    const subject = `Karabo Discovery Readout — ${sessionData.customerName}`
    const body = buildTeamsSummary({
      customerName: sessionData.customerName,
      topUseCases: (sessionData.useCases || []).slice(0, 5).map((u) => ({
        title: u.title, annualCoiUSD: u.coiEstimate?.totalAnnualCOI,
      })),
      threeYearBenefitUSD: sessionData.businessCase?.threeYearBenefitUSD,
      paybackMonths: sessionData.businessCase?.paybackMonths,
    })
    openOutlookCompose({ subject, body })
    toast.success('Opening Outlook…')
  }

  const handleExportPDF = () => {
    onExportPDF(effortUnit)
    onOpenChange(false)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FilePdf size={24} weight="duotone" className="text-red-600" />
            Export Assessment Report
          </DialogTitle>
          <DialogDescription>
            Generate a comprehensive PDF report with all metrics, analyses, and AI insights
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          <div className="space-y-3">
            <Label className="text-sm font-semibold">Effort Unit Display</Label>
            <RadioGroup value={effortUnit} onValueChange={(value) => setEffortUnit(value as any)}>
              <div className="flex items-start space-x-2">
                <RadioGroupItem value="person-weeks" id="person-weeks" className="mt-0.5" />
                <div className="flex-1">
                  <Label htmlFor="person-weeks" className="font-medium cursor-pointer">
                    Person-Weeks
                  </Label>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Default unit for effort estimation (e.g., 4 person-weeks)
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-2">
                <RadioGroupItem value="fte" id="fte" className="mt-0.5" />
                <div className="flex-1">
                  <Label htmlFor="fte" className="font-medium cursor-pointer">
                    FTE (Full-Time Equivalents)
                  </Label>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Convert to years (person-weeks ÷ 52, e.g., 4 weeks = 0.077 FTE)
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-2">
                <RadioGroupItem value="man-hours" id="man-hours" className="mt-0.5" />
                <div className="flex-1">
                  <Label htmlFor="man-hours" className="font-medium cursor-pointer">
                    Man-Hours
                  </Label>
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Convert to hours (person-weeks × 40, e.g., 4 weeks = 160 hours)
                  </p>
                </div>
              </div>
            </RadioGroup>
          </div>

          <div className="bg-muted/50 rounded-lg p-4 space-y-2">
            <h4 className="font-medium text-sm">Report Contents</h4>
            <ul className="text-xs text-muted-foreground space-y-1">
              <li>✓ Customer Information & Metadata</li>
              <li>✓ AI-Generated Executive Summary</li>
              <li>✓ Scoring Methodology Explanation</li>
              <li>✓ Top Recommendations with AI Rationales</li>
              <li>✓ Complete Use Case Analysis</li>
              <li>✓ KPI Mappings & Metrics</li>
            </ul>
          </div>

          <Separator />

          <div className="space-y-3">
            <Label className="text-sm font-semibold">Quick Export Options</Label>
            <div className="grid grid-cols-2 gap-2">
              <Button
                variant="outline"
                onClick={handleCopyEmailHTML}
                disabled={!sessionData}
                className="gap-2"
              >
                {emailCopied ? (
                  <CheckCircle size={16} className="text-green-600" />
                ) : (
                  <Envelope size={16} />
                )}
                {emailCopied ? 'Copied!' : 'Email HTML'}
              </Button>
              <Button
                variant="outline"
                onClick={handlePrintPDF}
                className="gap-2"
              >
                <Printer size={16} />
                Print to PDF
              </Button>
              <Button
                variant="outline"
                onClick={handleExportPPTX}
                disabled={!sessionData}
                className="gap-2"
              >
                <MicrosoftPowerpointLogo size={16} className="text-orange-600" />
                PowerPoint
              </Button>
              <Button
                variant="outline"
                onClick={handleShareTeams}
                disabled={!sessionData}
                className="gap-2"
              >
                <MicrosoftTeamsLogo size={16} className="text-purple-600" />
                Share in Teams
              </Button>
              <Button
                variant="outline"
                onClick={handleShareOutlook}
                disabled={!sessionData}
                className="col-span-2 gap-2"
              >
                <MicrosoftOutlookLogo size={16} className="text-blue-600" />
                Send via Outlook
              </Button>
            </div>
            {!sessionData && (
              <p className="text-xs text-muted-foreground">
                Quick exports require an active session with use cases
              </p>
            )}
          </div>
        </div>

        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleExportPDF} className="gap-2">
            <FilePdf size={18} weight="bold" />
            Export PDF Report
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
