import type { ServiceDef } from './types'

/**
 * Curated catalog of services frequently encountered in Innovation Hub
 * envisioning sessions. Azure-first, plus the most common third-party
 * platforms a customer is likely to already own.
 *
 * fitScore (0-100): higher = preferred when multiple services satisfy the
 * same capability in the best-fit path.
 */
export const SERVICE_CATALOG: ServiceDef[] = [
  // ── Azure: App & AI ─────────────────────────────────────────
  {
    id: 'azure-foundry',
    name: 'Microsoft Foundry',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['llm-hosting', 'embeddings', 'agent-orchestration', 'responsible-ai-evals'],
    fitScore: 95,
    sovereignReady: true,
    rationale: 'Unified AI platform for models, agents, evals, and grounding.',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI Service',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['llm-hosting', 'embeddings'],
    fitScore: 90,
    sovereignReady: true,
    rationale: 'Enterprise-grade access to OpenAI models in Azure.',
  },
  {
    id: 'azure-content-safety',
    name: 'Azure AI Content Safety',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['content-safety', 'jailbreak-detection'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-apim-ai-gateway',
    name: 'Azure API Management (AI Gateway)',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['ai-gateway', 'api-management'],
    fitScore: 92,
    sovereignReady: true,
    rationale: 'Token limits, semantic caching, content safety, and load balancing for AI backends.',
  },
  {
    id: 'azure-doc-intel',
    name: 'Azure AI Document Intelligence',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['document-intelligence', 'vision-ocr'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-speech',
    name: 'Azure AI Speech',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['speech-to-text', 'text-to-speech'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'azure-app-service',
    name: 'Azure App Service',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['app-hosting-web'],
    fitScore: 85,
    sovereignReady: true,
  },
  {
    id: 'azure-container-apps',
    name: 'Azure Container Apps',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['app-hosting-container'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-functions',
    name: 'Azure Functions',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['app-hosting-serverless'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'azure-logic-apps',
    name: 'Azure Logic Apps',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['workflow-orchestration', 'integration-connectors'],
    fitScore: 80,
    sovereignReady: true,
  },
  {
    id: 'azure-event-hubs',
    name: 'Azure Event Hubs',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['event-streaming'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-service-bus',
    name: 'Azure Service Bus',
    vendor: 'azure',
    layer: 'app-ai',
    capabilities: ['messaging-queue'],
    fitScore: 90,
    sovereignReady: true,
  },

  // ── Microsoft 365 surfaces ──────────────────────────────────
  {
    id: 'm365-teams',
    name: 'Microsoft Teams',
    vendor: 'microsoft-365',
    layer: 'app-ai',
    capabilities: ['ux-surface-teams'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'm365-copilot',
    name: 'Microsoft 365 Copilot',
    vendor: 'microsoft-365',
    layer: 'app-ai',
    capabilities: ['ux-surface-copilot'],
    fitScore: 92,
    sovereignReady: true,
  },
  {
    id: 'power-platform',
    name: 'Power Platform',
    vendor: 'microsoft-365',
    layer: 'app-ai',
    capabilities: ['ux-surface-power-platform', 'workflow-orchestration', 'integration-connectors'],
    fitScore: 80,
    sovereignReady: true,
  },

  // ── Azure: Data ─────────────────────────────────────────────
  {
    id: 'azure-sql',
    name: 'Azure SQL Database',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['relational-db'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-cosmos',
    name: 'Azure Cosmos DB',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['nosql-db', 'vector-store'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-ai-search',
    name: 'Azure AI Search',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['search-index', 'vector-store'],
    fitScore: 95,
    sovereignReady: true,
    rationale: 'Hybrid (keyword + vector + semantic) search optimized for RAG.',
  },
  {
    id: 'azure-fabric',
    name: 'Microsoft Fabric',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['lakehouse', 'analytical-store', 'data-pipeline'],
    fitScore: 92,
    sovereignReady: true,
  },
  {
    id: 'azure-data-factory',
    name: 'Azure Data Factory',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['data-pipeline', 'integration-connectors'],
    fitScore: 85,
    sovereignReady: true,
  },
  {
    id: 'azure-purview',
    name: 'Microsoft Purview',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['data-governance', 'data-classification', 'dlp'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-storage',
    name: 'Azure Blob Storage / ADLS',
    vendor: 'azure',
    layer: 'data',
    capabilities: ['object-storage'],
    fitScore: 92,
    sovereignReady: true,
  },

  // ── Azure: Infrastructure ───────────────────────────────────
  {
    id: 'azure-vnet',
    name: 'Azure Virtual Network + Private Endpoints',
    vendor: 'azure',
    layer: 'infrastructure',
    capabilities: ['private-networking'],
    fitScore: 92,
    sovereignReady: true,
  },
  {
    id: 'azure-front-door',
    name: 'Azure Front Door',
    vendor: 'azure',
    layer: 'infrastructure',
    capabilities: ['cdn-edge', 'waf'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'azure-aks',
    name: 'Azure Kubernetes Service',
    vendor: 'azure',
    layer: 'infrastructure',
    capabilities: ['kubernetes-platform', 'app-hosting-container'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions + Bicep/Terraform',
    vendor: 'azure',
    layer: 'infrastructure',
    capabilities: ['iac-pipeline'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'azure-monitor',
    name: 'Azure Monitor + App Insights',
    vendor: 'azure',
    layer: 'infrastructure',
    capabilities: ['observability-logs', 'observability-metrics', 'observability-traces'],
    fitScore: 90,
    sovereignReady: true,
  },

  // ── Azure: Identity & Security ──────────────────────────────
  {
    id: 'entra-id',
    name: 'Microsoft Entra ID',
    vendor: 'azure',
    layer: 'identity',
    capabilities: ['workforce-identity', 'managed-identity'],
    fitScore: 95,
    sovereignReady: true,
  },
  {
    id: 'entra-external-id',
    name: 'Microsoft Entra External ID',
    vendor: 'azure',
    layer: 'identity',
    capabilities: ['consumer-identity'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'entra-agent-id',
    name: 'Microsoft Entra Agent ID',
    vendor: 'azure',
    layer: 'identity',
    capabilities: ['agent-identity'],
    fitScore: 92,
    sovereignReady: true,
    rationale: 'First-class identity for autonomous agents with OAuth token exchange.',
  },
  {
    id: 'entra-pim',
    name: 'Entra Privileged Identity Management',
    vendor: 'azure',
    layer: 'identity',
    capabilities: ['privileged-access-mgmt'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'azure-key-vault',
    name: 'Azure Key Vault',
    vendor: 'azure',
    layer: 'security',
    capabilities: ['secrets-mgmt', 'key-mgmt-cmk'],
    fitScore: 92,
    sovereignReady: true,
  },
  {
    id: 'azure-ddos',
    name: 'Azure DDoS Protection',
    vendor: 'azure',
    layer: 'security',
    capabilities: ['ddos-protection'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'defender-cloud',
    name: 'Microsoft Defender for Cloud',
    vendor: 'azure',
    layer: 'security',
    capabilities: ['cloud-posture-mgmt'],
    fitScore: 90,
    sovereignReady: true,
  },
  {
    id: 'sentinel',
    name: 'Microsoft Sentinel',
    vendor: 'azure',
    layer: 'security',
    capabilities: ['siem'],
    fitScore: 90,
    sovereignReady: true,
  },

  // ── Azure: Operations ───────────────────────────────────────
  {
    id: 'azure-cost-mgmt',
    name: 'Microsoft Cost Management',
    vendor: 'azure',
    layer: 'operations',
    capabilities: ['cost-mgmt'],
    fitScore: 88,
    sovereignReady: true,
  },
  {
    id: 'azure-quota',
    name: 'Azure Quota & Capacity Reservations',
    vendor: 'azure',
    layer: 'operations',
    capabilities: ['capacity-mgmt'],
    fitScore: 85,
    sovereignReady: true,
  },
  {
    id: 'azure-backup',
    name: 'Azure Backup + Site Recovery',
    vendor: 'azure',
    layer: 'operations',
    capabilities: ['backup-dr'],
    fitScore: 88,
    sovereignReady: true,
  },

  // ── Common third-party platforms ────────────────────────────
  {
    id: 'snowflake',
    name: 'Snowflake',
    vendor: 'snowflake',
    layer: 'data',
    capabilities: ['analytical-store', 'lakehouse', 'data-governance'],
    fitScore: 80,
    sovereignReady: false,
    rationale: 'Common incumbent warehouse — reuse if customer already has it.',
  },
  {
    id: 'databricks',
    name: 'Azure Databricks',
    vendor: 'databricks',
    layer: 'data',
    capabilities: ['lakehouse', 'analytical-store', 'data-pipeline', 'embeddings'],
    fitScore: 85,
    sovereignReady: true,
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    vendor: 'salesforce',
    layer: 'app-ai',
    capabilities: ['integration-connectors'],
    fitScore: 70,
    sovereignReady: false,
  },
  {
    id: 'sap',
    name: 'SAP',
    vendor: 'sap',
    layer: 'app-ai',
    capabilities: ['integration-connectors'],
    fitScore: 70,
    sovereignReady: false,
  },
  {
    id: 'servicenow',
    name: 'ServiceNow',
    vendor: 'servicenow',
    layer: 'app-ai',
    capabilities: ['workflow-orchestration', 'integration-connectors'],
    fitScore: 75,
    sovereignReady: false,
  },
  {
    id: 'okta',
    name: 'Okta',
    vendor: 'other',
    layer: 'identity',
    capabilities: ['workforce-identity', 'consumer-identity'],
    fitScore: 78,
    sovereignReady: false,
  },
  {
    id: 'aws-s3',
    name: 'AWS S3',
    vendor: 'aws',
    layer: 'data',
    capabilities: ['object-storage'],
    fitScore: 70,
    sovereignReady: false,
  },
  {
    id: 'aws-rds',
    name: 'AWS RDS',
    vendor: 'aws',
    layer: 'data',
    capabilities: ['relational-db'],
    fitScore: 70,
    sovereignReady: false,
  },
]

export const SERVICE_BY_ID: Record<string, ServiceDef> = SERVICE_CATALOG.reduce(
  (acc, s) => {
    acc[s.id] = s
    return acc
  },
  {} as Record<string, ServiceDef>,
)
