/**
 * Pure converter: BlueprintResult → Mermaid `flowchart TB` source.
 * Determinism guaranteed (stable component ordering by layer + capability).
 */

import type { BlueprintLayer, BlueprintPathKind, BlueprintResult, Blueprint, BlueprintComponent } from '@/lib/solution-blueprint/types'
import { BLUEPRINT_LAYER_LABELS } from '@/lib/solution-blueprint/types'
import { deriveEdges, LAYER_ORDER } from './edges'
import { STATE_COLORS } from './diagram-themes'

const LAYER_ICON: Record<BlueprintLayer, string> = {
  'app-ai': 'Application & AI',
  data: 'Data',
  infrastructure: 'Infrastructure',
  identity: 'Identity',
  security: 'Security',
  operations: 'Operations',
}

function nodeId(capability: string) {
  return `n_${capability.replace(/[^a-zA-Z0-9_]/g, '_')}`
}

function escapeLabel(s: string) {
  // Mermaid needs quotes for spaces / special chars; double-quotes within
  // labels need to be replaced.
  return s.replace(/"/g, '\\"').replace(/\n/g, ' ')
}

function classFor(c: BlueprintComponent) {
  if (c.gap) return 'gap'
  if (c.reused) return 'reused'
  return 'netNew'
}

export function toMermaid(result: BlueprintResult, path: BlueprintPathKind): string {
  const blueprint: Blueprint = path === 'best-fit' ? result.bestFit : result.estateOptimized
  const lines: string[] = []
  lines.push('%% Generated by KARABO Solution Blueprint')
  lines.push(`%% Path: ${path}  Use case: ${result.useCase.name}`)
  lines.push('flowchart TB')

  // Class definitions
  lines.push(`  classDef reused fill:${STATE_COLORS.reused.fill},stroke:${STATE_COLORS.reused.stroke},color:${STATE_COLORS.reused.text},stroke-width:2px;`)
  lines.push(`  classDef netNew fill:${STATE_COLORS.netNew.fill},stroke:${STATE_COLORS.netNew.stroke},color:${STATE_COLORS.netNew.text},stroke-width:1.5px;`)
  lines.push(`  classDef gap    fill:${STATE_COLORS.gap.fill},stroke:${STATE_COLORS.gap.stroke},color:${STATE_COLORS.gap.text},stroke-width:1.5px,stroke-dasharray:4 3;`)

  // Group components by layer using the well-known LAYER_ORDER.
  const byLayer = new Map<BlueprintLayer, BlueprintComponent[]>()
  for (const layer of LAYER_ORDER) byLayer.set(layer, [])
  for (const c of blueprint.components) {
    if (!byLayer.has(c.layer)) byLayer.set(c.layer, [])
    byLayer.get(c.layer)!.push(c)
  }

  for (const layer of LAYER_ORDER) {
    const items = (byLayer.get(layer) ?? []).slice().sort((a, b) => a.capability.localeCompare(b.capability))
    if (items.length === 0) continue
    lines.push(`  subgraph ${nodeId('layer_' + layer)}["${escapeLabel(BLUEPRINT_LAYER_LABELS[layer] ?? LAYER_ICON[layer])}"]`)
    lines.push('    direction TB')
    for (const c of items) {
      const id = nodeId(c.capability)
      const label = c.service
        ? `${escapeLabel(c.service.name)}<br/><span style='font-size:11px;opacity:.75'>${escapeLabel(c.capabilityName)}</span>`
        : `${escapeLabel(c.capabilityName)}<br/><span style='font-size:11px;color:#7F1D1D'>(gap)</span>`
      lines.push(`    ${id}["${label}"]:::${classFor(c)}`)
    }
    lines.push('  end')
  }

  // Edges
  const edges = deriveEdges(blueprint)
  for (const e of edges) {
    const arrow = e.kind === 'observe' ? '-.->' : e.kind === 'auth' ? '-.->' : '-->'
    const label = e.label ? `|${escapeLabel(e.label)}|` : ''
    lines.push(`  ${nodeId(e.fromCapability)} ${arrow}${label} ${nodeId(e.toCapability)}`)
  }

  return lines.join('\n')
}
