import { Badge } from '@/components/ui/badge'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'
import { UserCircle, Stack, ChatCircleText, Sparkle, ChartLine, Briefcase, Newspaper, MagnifyingGlass } from '@phosphor-icons/react'
import type { Icon } from '@phosphor-icons/react'

export type UseCaseSource = 'ai-generated' | 'manual' | 'fallback' | 'discovery' | 'earnings' | 'financials' | 'news' | 'industry-research'

interface UseCaseSourceBadgeProps {
  source: UseCaseSource
  size?: 'sm' | 'md'
}

const SOURCE_CONFIG: Record<UseCaseSource, {
  label: string
  description: string
  icon: Icon
  colors: string
}> = {
  'ai-generated': {
    label: 'AI Generated',
    description: 'Generated by AI based on discovery data and analysis',
    icon: Sparkle,
    colors: 'bg-purple-500/10 text-purple-600 border-purple-500/30',
  },
  'manual': {
    label: 'Manual',
    description: 'Manually added during the discovery workflow',
    icon: UserCircle,
    colors: 'bg-blue-500/10 text-blue-600 border-blue-500/30',
  },
  'fallback': {
    label: 'Industry Template',
    description: 'Pre-configured use case based on industry best practices',
    icon: Stack,
    colors: 'bg-amber-500/10 text-amber-600 border-amber-500/30',
  },
  'discovery': {
    label: 'Discovery',
    description: 'Based on discovery Q&A session responses',
    icon: ChatCircleText,
    colors: 'bg-gray-500/10 text-gray-600 border-gray-500/30',
  },
  'earnings': {
    label: 'Earnings',
    description: 'Based on earnings call transcripts',
    icon: ChartLine,
    colors: 'bg-blue-500/10 text-blue-600 border-blue-500/30',
  },
  'financials': {
    label: 'Financials',
    description: 'Based on financial statements & metrics',
    icon: Briefcase,
    colors: 'bg-green-500/10 text-green-600 border-green-500/30',
  },
  'news': {
    label: 'News',
    description: 'Based on recent company news & market sentiment',
    icon: Newspaper,
    colors: 'bg-orange-500/10 text-orange-600 border-orange-500/30',
  },
  'industry-research': {
    label: 'Industry',
    description: 'Based on industry trends & standards',
    icon: MagnifyingGlass,
    colors: 'bg-purple-500/10 text-purple-600 border-purple-500/30',
  },
}

export function UseCaseSourceBadge({ source, size = 'sm' }: UseCaseSourceBadgeProps) {
  const config = SOURCE_CONFIG[source]
  if (!config) return null

  const Icon = config.icon
  const sizeClasses = size === 'sm' 
    ? 'text-[10px] px-1.5 py-0.5 h-5' 
    : 'text-xs px-2 py-1'
  const iconSize = size === 'sm' ? 10 : 14

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Badge variant="outline" className={`${sizeClasses} ${config.colors}`}>
            <Icon size={iconSize} className="mr-1" weight="bold" />
            {config.label}
          </Badge>
        </TooltipTrigger>
        <TooltipContent>
          <p className="text-xs">{config.description}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}

interface UseCaseSourceBadgesProps {
  dataSources?: UseCaseSource[]
  showPrimaryOnly?: boolean
  size?: 'sm' | 'md'
}

/**
 * Displays badges for use case data sources
 * Primary sources (ai-generated, manual, fallback) are shown first
 * Secondary sources (earnings, financials, news, etc.) shown after
 */
export function UseCaseSourceBadges({ dataSources, showPrimaryOnly = false, size = 'sm' }: UseCaseSourceBadgesProps) {
  if (!dataSources || dataSources.length === 0) return null

  // Primary sources indicate how the use case was created
  const primarySources: UseCaseSource[] = ['ai-generated', 'manual', 'fallback']
  const secondarySources: UseCaseSource[] = ['earnings', 'financials', 'news', 'industry-research', 'discovery']

  const primary = dataSources.filter(s => primarySources.includes(s))
  const secondary = dataSources.filter(s => secondarySources.includes(s))

  return (
    <div className="flex flex-wrap gap-1.5">
      {/* Always show primary source badges */}
      {primary.map(source => (
        <UseCaseSourceBadge key={source} source={source} size={size} />
      ))}
      
      {/* Show secondary sources only if not showPrimaryOnly */}
      {!showPrimaryOnly && secondary.map(source => (
        <UseCaseSourceBadge key={source} source={source} size={size} />
      ))}
    </div>
  )
}
